### ISSUE TITLE
Docker image build error 

### ISSUE THREAD

**Issue by godfather68** [IBM/MAX-Image-Resolution-Enhancer#50] opened 2021-11-29 13:57 UTC
Hi, 

I am having trouble while building the image. I get the following error:

![Screenshot from 2021-11-29 14-55-37](https://user-images.githubusercontent.com/12661640/143880660-885e0a4e-9b7e-4746-8001-34ff4b41f5e0.png)
 
Is the this repo still maintained ? 

Any help would be much appreciated.

**Comment by Sid-MB** [comment] 2021-12-06 04:25
I'm having the same problem. It looks like the Dockerfile references a website that doesn't exist anymore?

https://github.com/IBM/MAX-Image-Resolution-Enhancer/blob/b1f179c75069451a0c453b8429b9f29ef93069d4/Dockerfile#L19

My web browser says it "can't find the server".

I'm no expert here; I am not sure what the solution is.
Did you find a workaround?

**Comment by godfather68** [comment] 2021-12-06 09:25
Hey, @Sid-MB 

Instead of using this repo, simply use the model official image from the Dockerhub. You can find the link down here 

[https://developer.ibm.com/exchanges/models/all/max-image-resolution-enhancer/](url)

Hope this can help solve your problem.

**Comment by Sid-MB** [comment] 2021-12-12 18:23
> Hey, @Sid-MB 
> 
> 
> 
> Instead of using this repo, simply use the model official image from the Dockerhub. You can find the link down here 
> 
> 
> 
> [https://developer.ibm.com/exchanges/models/all/max-image-resolution-enhancer/](url)
> 
> 
> 
> Hope this can help solve your problem.

That worked, thank you!

**Comment by sorenwacker** [comment] 2021-12-16 19:25
That is a dead link not as well.

**Comment by AlexKalopsia** [comment] 2022-01-02 15:44
@sorenwacker weirdly enough, that link in this thread just points to the wrong location, but just putting the url in the browser will lead you to the correct location in the ibm dev docs

**Comment by vasilzhigilei** [comment] 2022-01-11 20:36
@godfather68 that link just redirects here https://github.com/IBM/MAX-Image-Resolution-Enhancer/issues/url

Still not sure how to resolve this issue.

**Comment by AlexKalopsia** [comment] 2022-01-11 20:52
As I said above, you need to just go to the link text URL (and not the embedded one)

https://developer.ibm.com/exchanges/models/all/max-image-resolution-enhancer/

**Comment by kmh4321** [comment] 2022-03-09 17:49
Hello @AlexKalopsia, @godfather68, @vasilzhigilei, 

thank you for your patience, the issue is now fixed: https://github.com/IBM/MAX-Image-Resolution-Enhancer/pull/55

**Closed** 2022-03-09 17:49 UTC
